spring:
    h2.console.enabled: true
    thymeleaf:
      mode: HTML5
      cache: false 
    main:
     web-environment: true  
logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
server:
   session.timeout: 300    
  
#spring.datasource.url = jdbc:h2:file:${biking2.database-file:${user.dir}/var/dev/db/biking-dev};FILE_LOCK=FS
#spring.datasource.username = ${biking2.database-username:biking2}
#spring.datasource.password = ${biking2.database-password:biking2}
#spring.datasource.driverClassName = org.h2.Driver             