#server:
  #port: 8443
  #ssl:
    #key-store: classpath:keystore.p12
    #key-store-password: Trabant601_
    #key-password: Trabant601_
    #key-store-type: PKCS12
spring:
    h2.console.enabled: true
    thymeleaf:
      mode: HTML5
      cache: false 
logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN           