spring:
    h2.console.enabled: true
    thymeleaf:
      mode: HTML5
      cache: false 
    main:
     web-environment: true
    datasource.initialize: true  
    #datasource.data: classpath*:import.sql
    mail:
      # TODO Benutze ZOHO-Account zum Versenden der Emails. zoho funktioniert nicht, googlemail funktioniert
      host: smtp.strato.de
      password: n5WEmRsGXuU/xWkGDs8rWw==
      username: info@andre-goldmann.de
      port: 465
      from: info@computing-for-kids.de
      subject: Registration
logging:
  level:
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
server:
   session.timeout: 300    
  
  # TODO man kann auch noch den Benutzername verschluesseln
      
#spring.datasource.url = jdbc:h2:file:${biking2.database-file:${user.dir}/var/dev/db/biking-dev};FILE_LOCK=FS
#spring.datasource.username = ${biking2.database-username:biking2}
#spring.datasource.password = ${biking2.database-password:biking2}
#spring.datasource.driverClassName = org.h2.Driver             