server:
    port: 9000
    session.timeout: 300
spring:
  thymeleaf:
      mode: HTML5
      cache: false
  main:
     web-environment: true
  mail:
      host: smtp.strato.de
      password: ENC(a4RmqdcQHOe1MXpaK3bDv6d35W1Witay)
      username: info@andre-goldmann.de
      port: 465
      from: info@computing-for-kids.de
      subject: Registration    
logging:
  level:
    com.ulisesbocchio.jasyptspringboot: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN              
---

spring:
    profiles: development
    h2.console.enabled: true
server:
    port: 8080 
---

spring:
    profiles: production
    datasource:
      driver-class-name: com.mysql.jdbc.Driver 
      url:  jdbc:mysql://localhost:3306/cfk
      username: cfk
      password:  ENC(0rLh75nem1Q2ZK74T6Vq+IZmyy/a3Gyj)
    jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      show-sql:  false
      hibernate:
        ddl-auto: update   
server:
    port: 9000

   
       